# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{decisiontree}
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ilya Grigorik"]
  s.date = %q{2010-10-03}
  s.description = %q{ID3-based implementation of the M.L. Decision Tree algorithm}
  s.email = %q{ilya@igvita.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "CHANGELOG.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "decisiontree.gemspec",
     "examples/continuous-id3.rb",
     "examples/data/continuous-test.txt",
     "examples/data/continuous-training.txt",
     "examples/data/discrete-test.txt",
     "examples/data/discrete-training.txt",
     "examples/discrete-id3.rb",
     "examples/simple.rb",
     "lib/decisiontree.rb",
     "lib/decisiontree/id3_tree.rb",
     "test/helper.rb",
     "test/test_decisiontree.rb"
  ]
  s.homepage = %q{http://github.com/igrigorik/decisiontree}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{decisiontree}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{ID3-based implementation of the M.L. Decision Tree algorithm}
  s.test_files = [
    "test/helper.rb",
     "test/test_decisiontree.rb",
     "examples/continuous-id3.rb",
     "examples/discrete-id3.rb",
     "examples/simple.rb"
  ]
  s.add_runtime_dependency "graphr"
  
  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

